# Generated by Django 3.2.6 on 2021-08-17 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 17, 17, 49, 50, 718585, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Not provided', max_length=200),
        ),
    ]
